### ISSUE TITLE
how can i fix bug>

### ISSUE THREAD

**Issue by smaster007** [jmohan57/cs-case-sim#25]
![image](https://github.com/jmohan57/cs-case-sim/assets/171212701/b2c051c5-8bf1-4c3f-9feb-ffc74e3364d3)

**Comment by venomsnake0777** [comment]
okay, you can use the prettier extension. 😁

**Comment by venomsnake0777** [comment]
?

**Comment by venomsnake0777** [comment]
???

**Comment by venomsnake0777** [comment]
adfdsaf
